services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: server
    # environment:
    #   - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5431/typoracer
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:17-alpine
    container_name: typo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: typoracer
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d typoracer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
